_format_version: "3.0"
_transform: true

services:
  - name: nginx-service
    url: http://nginx.default.svc.cluster.local:80
    routes:
      - name: nginx-route
        paths:
          - /nginx
        strip_path: true
