apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-dbless-config
  namespace: kong
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: nginx-service
        url: http://nginx.default.svc.cluster.local
        routes:
          - name: nginx-route
            paths:
              - /nginx
            strip_path: true
