ingressController:
  enabled: true
  installCRDs: true

proxy:
  type: LoadBalancer
  http:
    enabled: true
  tls:
    enabled: true

admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 32001

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: true

env:
  database: "off"
  KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml

extraVolumes:
  - name: kong-dbless-config
    configMap:
      name: kong-dbless-config

extraVolumeMounts:
  - name: kong-dbless-config
    mountPath: /kong/declarative
    readOnly: true
