ingressController:
  enabled: false

proxy:
  type: LoadBalancer
  http:
    enabled: true
  tls:
    enabled: true

admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 32001

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: true

env:
  database: "off"
  declarative_config: /kong/declarative/kong.yaml

deployment:
  userDefinedVolumes:
    - name: kong-dbless-config
      configMap:
        name: kong-dbless-config

  userDefinedVolumeMounts:
    - name: kong-dbless-config
      mountPath: /kong/declarative
      readOnly: true